# Generated by Django 3.2.4 on 2021-06-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_alter_document_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated:'),
        ),
    ]
